### ISSUE TITLE
Confusing docLocation on missing key (and crash)

### ISSUE THREAD

**Issue by ysangkok** [velveteer/hermes#1]
```
*Data.Hermes> newtype Person = Person Int deriving Show
*Data.Hermes> 
*Data.Hermes> personDecoder = withObject $ \obj -> Person <$> atKey "lol" int obj
*Data.Hermes> decodeEither personDecoder "{}"
Left (SIMDException (HError {path = "/lol", errorMsg = "The JSON field referenced does not exist in this object.", docLocation = "/\DEL", docDebug = "json_iterator [ depth : 0, structural : 'n', offset : 2', error : No error ]"}))
```

What does the "/\DEL" mean here? I am worried that it is accessing something out of bounds. I would expect the location to be `/`.

So I tried running it a few times and something is definitely wrong here:

```
*Data.Hermes> decodeEither personDecoder "{}"
*** Exception: Cannot decode byte '\xb8': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
*Data.Hermes> decodeEither personDecoder "{}"
cabal: repl failed for hermes-json-0.1.0.0. The build process segfaulted (i.e.
SIGSEGV).
```

This is on Debian Bullseye and ghc 8.10.7 from ghcup and commit 
``` 
commit a3fe3eb9d8da07295d7c7ac3030dc5daaf89f27f (HEAD -> master, origin/master, origin/HEAD)
Author: Josh Miller <notjoshmiller@gmail.com>
Date:   Tue Nov 2 17:18:48 2021 -0500

    use CStringLen for JSON pointer as well
```

**Comment by velveteer** [comment]
Thanks for reporting! I reproduced it locally, and I think the problem is I forgot to handle the `OUT_OF_BOUNDS` error coming from `simdjson::document::current_location()`. So this leads to bad things. I am also seeing some odd behavior with marshaling the debug string. I will work on getting a fix pushed up for this.

**Comment by velveteer** [comment]
There were several bugs at play here I think. I made the mistake of using a `padded_string_view` instead of a `padded_string`, so the current location would read into extra memory if we reached the end of the document. Also there are some simdjson errors that do _not_ support calling `current_location()` once they are thrown, so those are now handled appropriately. And finally the `OUT_OF_BOUNDS` error from `current_location()` is now handled.
